### ISSUE TITLE
Offload ML workloads to an external microservice written in another language

### ISSUE THREAD

**Issue by daniwasonline** [spongedsc/pathways#104]
> ok actually tho rust seems to have a better set of ai stuff (huggingface candle, etc.) which in theory could be helpful if we hadnt already settled on cf ai

@artifishvr [in this issue](https://github.com/spongedsc/pathways/issues/103#issuecomment-2232625819)

Being serious about this comment, offloading ML workloads and other heavy-lifters/services to microservices outside of the JavaScript context is plausible. While we have settled on Workers AI, the adapter specification that we use is universal. It can be adopted to nearly any service/API - in fact, it already has, with Integrations using an OpenAI adapter using (relatively) the same layout for command detection.

This should be explored in the future.

**Comment by Butterroach** [comment]
why did you write it professionally

**Comment by artifishvr** [comment]
dani you just tagged some random bot account that is not me

**Comment by daniwasonline** [comment]
shit

**Comment by Butterroach** [comment]
why can i edit other people's comments why is that a thing

**Comment by Butterroach** [comment]
https://artifish.github.io/artifish.il/

**Comment by daniwasonline** [comment]
> why did you write it professionally

read #77

**Comment by daniwasonline** [comment]
# An update
Pathways Engine (PWSE) will be the all-in-one replacement system for all history, integration, and inference going forward. While the original plan was to write PWSE in another language other than JavaScript, the lack of a reliable LangChain library in an easily-prototyped language led to an initial version being written in TypeScript (with Bun).

I may explore the possibility of rewriting PWSE in Go when its' LangChain library is mature enough to support most features required to practically do so. I might also consider writing it in Rust, but the slow pace of scaffolding and prototyping new features makes this highly unlikely.
