### ISSUE TITLE
[missing-v2] ai does not have memory

### ISSUE THREAD

**Issue by Butterroach** [spongedsc/pathways#108]
:trollface: (fuck you)

**Comment by Butterroach** [comment]
wrong label but

**Comment by Butterroach** [comment]
ill keep it for funny

**Comment by lordsirggg** [comment]
I’m a little sigma short and stout here is my gyatt rizz here is my gout

**Comment by Butterroach** [comment]
im stupid
![image](https://github.com/user-attachments/assets/32e70b82-1efc-443c-880d-6b75a59a5d5a)

**Comment by Butterroach** [comment]
i closed it

**Comment by Butterroach** [comment]
what

**Comment by Butterroach** [comment]
the bot was probably just confused from the huge amount of the converstaion history
